name: validate

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/action@main
        with:
          category: integration

  hassfest:
    name: hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: home-assistant/actions/hassfest@master
